FROM python:3.12.2

RUN apt-get update
RUN apt-get install -y vim tree git

RUN python3 -m pip install --upgrade pip
RUN pip3 install numpy matplotlib pandas dash dash-mantine-components

# install flowfunc
RUN pip3 install git+https://github.com/idling-mind/flowfunc.git

# ユーザーを作成
ARG UID=1000
RUN useradd -m -u ${UID} user

# プロジェクトフォルダを/codeに追加する。ユーザー権限で扱えるようchownオプションを使う。
# ADDの実行権者はrootなのでオプションが必要。
ADD  --chown=user:user . /workdir
# RUN chown user:user -R /workdir

# 作成したユーザーに切り替える
# このユーザーはRUN, CMD, ENTRYPOINT, docker run, exec の実行ユーザ。
USER ${UID}

# 作成したフォルダに移動し、パッケージリストをインストールする。
WORKDIR /workdir
